# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTuiFrame_admini.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_admini(object):
    def setupUi(self, Frame_admini):
        Frame_admini.setObjectName("Frame_admini")
        Frame_admini.resize(712, 559)
        self.gridLayout = QtWidgets.QGridLayout(Frame_admini)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_back = QtWidgets.QPushButton(Frame_admini)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_2.addWidget(self.pushButton_back)
        self.pushButton_quit = QtWidgets.QPushButton(Frame_admini)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout_2.addWidget(self.pushButton_quit)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget_admini = QtWidgets.QTabWidget(Frame_admini)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_admini.setFont(font)
        self.tabWidget_admini.setObjectName("tabWidget_admini")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.gridLayout_8.addLayout(self.verticalLayout_9, 0, 0, 2, 1)
        self.lineEdit_msr_bno = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_msr_bno.setFont(font)
        self.lineEdit_msr_bno.setObjectName("lineEdit_msr_bno")
        self.gridLayout_8.addWidget(self.lineEdit_msr_bno, 0, 1, 1, 1)
        self.lineEdit_msr_bnum = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_msr_bnum.setFont(font)
        self.lineEdit_msr_bnum.setObjectName("lineEdit_msr_bnum")
        self.gridLayout_8.addWidget(self.lineEdit_msr_bnum, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_8)
        self.pushButton_msr_ensure = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_msr_ensure.setFont(font)
        self.pushButton_msr_ensure.setObjectName("pushButton_msr_ensure")
        self.verticalLayout_7.addWidget(self.pushButton_msr_ensure)
        self.gridLayout_9.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(199, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 2, 1, 1, 1)
        self.tabWidget_admini.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(20, 171, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 2, 1)
        self.lineEdit_mbr_bno = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_mbr_bno.setFont(font)
        self.lineEdit_mbr_bno.setObjectName("lineEdit_mbr_bno")
        self.gridLayout_2.addWidget(self.lineEdit_mbr_bno, 0, 1, 1, 1)
        self.lineEdit_mbr_bnum = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_mbr_bnum.setFont(font)
        self.lineEdit_mbr_bnum.setObjectName("lineEdit_mbr_bnum")
        self.gridLayout_2.addWidget(self.lineEdit_mbr_bnum, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.pushButton_mbr_ensure = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_mbr_ensure.setFont(font)
        self.pushButton_mbr_ensure.setObjectName("pushButton_mbr_ensure")
        self.verticalLayout_5.addWidget(self.pushButton_mbr_ensure)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 1, 1, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(199, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 2, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 3, 1, 1, 1)
        self.tabWidget_admini.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.widget = QtWidgets.QWidget(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2_book_add = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2_book_add.setFont(font)
        self.pushButton_2_book_add.setObjectName("pushButton_2_book_add")
        self.verticalLayout_3.addWidget(self.pushButton_2_book_add)
        self.pushButton_2_book_del = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2_book_del.setFont(font)
        self.pushButton_2_book_del.setObjectName("pushButton_2_book_del")
        self.verticalLayout_3.addWidget(self.pushButton_2_book_del)
        self.pushButton_2_book_change = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2_book_change.setFont(font)
        self.pushButton_2_book_change.setObjectName("pushButton_2_book_change")
        self.verticalLayout_3.addWidget(self.pushButton_2_book_change)
        self.horizontalLayout_6.addWidget(self.widget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2_search_see = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2_search_see.setFont(font)
        self.pushButton_2_search_see.setObjectName("pushButton_2_search_see")
        self.verticalLayout_2.addWidget(self.pushButton_2_search_see)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget_admini.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_salesMan = QtWidgets.QGridLayout()
        self.gridLayout_salesMan.setObjectName("gridLayout_salesMan")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.widget_3_button = QtWidgets.QWidget(self.tab_4)
        self.widget_3_button.setObjectName("widget_3_button")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3_button)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3_SM_add = QtWidgets.QPushButton(self.widget_3_button)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3_SM_add.setFont(font)
        self.pushButton_3_SM_add.setObjectName("pushButton_3_SM_add")
        self.verticalLayout_4.addWidget(self.pushButton_3_SM_add)
        self.pushButton_3_SM_change = QtWidgets.QPushButton(self.widget_3_button)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3_SM_change.setFont(font)
        self.pushButton_3_SM_change.setObjectName("pushButton_3_SM_change")
        self.verticalLayout_4.addWidget(self.pushButton_3_SM_change)
        self.pushButton_3_SM_del = QtWidgets.QPushButton(self.widget_3_button)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3_SM_del.setFont(font)
        self.pushButton_3_SM_del.setObjectName("pushButton_3_SM_del")
        self.verticalLayout_4.addWidget(self.pushButton_3_SM_del)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.addWidget(self.widget_3_button)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3_SM_view = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3_SM_view.setFont(font)
        self.pushButton_3_SM_view.setObjectName("pushButton_3_SM_view")
        self.verticalLayout.addWidget(self.pushButton_3_SM_view)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.gridLayout_salesMan.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_salesMan, 0, 0, 1, 1)
        self.tabWidget_admini.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_date_see = QtWidgets.QGridLayout()
        self.gridLayout_date_see.setObjectName("gridLayout_date_see")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_4_sr = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4_sr.setObjectName("pushButton_4_sr")
        self.horizontalLayout_4.addWidget(self.pushButton_4_sr)
        self.pushButton_4_br = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4_br.setObjectName("pushButton_4_br")
        self.horizontalLayout_4.addWidget(self.pushButton_4_br)
        self.pushButton_4_msr = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4_msr.setObjectName("pushButton_4_msr")
        self.horizontalLayout_4.addWidget(self.pushButton_4_msr)
        self.pushButton_4_mbr = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4_mbr.setObjectName("pushButton_4_mbr")
        self.horizontalLayout_4.addWidget(self.pushButton_4_mbr)
        self.pushButton_4_minfo = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4_minfo.setObjectName("pushButton_4_minfo")
        self.horizontalLayout_4.addWidget(self.pushButton_4_minfo)
        self.gridLayout_date_see.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_date_see, 0, 0, 1, 1)
        self.tabWidget_admini.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_admini_info = QtWidgets.QGridLayout()
        self.gridLayout_admini_info.setObjectName("gridLayout_admini_info")
        self.gridLayout_5.addLayout(self.gridLayout_admini_info, 0, 0, 1, 1)
        self.tabWidget_admini.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget_admini, 1, 0, 1, 1)

        self.retranslateUi(Frame_admini)
        self.tabWidget_admini.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Frame_admini)

    def retranslateUi(self, Frame_admini):
        _translate = QtCore.QCoreApplication.translate
        Frame_admini.setWindowTitle(_translate("Frame_admini", "管理员"))
        self.pushButton_back.setText(_translate("Frame_admini", "返回"))
        self.pushButton_quit.setText(_translate("Frame_admini", "退出"))
        self.label_3.setText(_translate("Frame_admini", "书号"))
        self.label_4.setText(_translate("Frame_admini", "数量"))
        self.pushButton_msr_ensure.setText(_translate("Frame_admini", "确认"))
        self.tabWidget_admini.setTabText(self.tabWidget_admini.indexOf(self.tab), _translate("Frame_admini", "图书入库"))
        self.label.setText(_translate("Frame_admini", "书号"))
        self.label_2.setText(_translate("Frame_admini", "数量"))
        self.pushButton_mbr_ensure.setText(_translate("Frame_admini", "确认"))
        self.tabWidget_admini.setTabText(self.tabWidget_admini.indexOf(self.tab_2), _translate("Frame_admini", "图书退货"))
        self.pushButton_2_book_add.setText(_translate("Frame_admini", "图书添加"))
        self.pushButton_2_book_del.setText(_translate("Frame_admini", "图书删除"))
        self.pushButton_2_book_change.setText(_translate("Frame_admini", "图书信息修改"))
        self.pushButton_2_search_see.setText(_translate("Frame_admini", "图书信息\n"
"搜索 查看"))
        self.tabWidget_admini.setTabText(self.tabWidget_admini.indexOf(self.tab_3), _translate("Frame_admini", "本地图书管理"))
        self.pushButton_3_SM_add.setText(_translate("Frame_admini", "添加"))
        self.pushButton_3_SM_change.setText(_translate("Frame_admini", "修改"))
        self.pushButton_3_SM_del.setText(_translate("Frame_admini", "删除"))
        self.pushButton_3_SM_view.setText(_translate("Frame_admini", "查看"))
        self.tabWidget_admini.setTabText(self.tabWidget_admini.indexOf(self.tab_4), _translate("Frame_admini", "销售人员管理"))
        self.pushButton_4_sr.setText(_translate("Frame_admini", "销售记录"))
        self.pushButton_4_br.setText(_translate("Frame_admini", "退货记录"))
        self.pushButton_4_msr.setText(_translate("Frame_admini", "入库记录"))
        self.pushButton_4_mbr.setText(_translate("Frame_admini", "出库记录"))
        self.pushButton_4_minfo.setText(_translate("Frame_admini", "会员信息"))
        self.tabWidget_admini.setTabText(self.tabWidget_admini.indexOf(self.tab_6), _translate("Frame_admini", "数据查看"))
        self.tabWidget_admini.setTabText(self.tabWidget_admini.indexOf(self.tab_5), _translate("Frame_admini", "个人信息管理"))

