# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTuiFrame_admini_info.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_admini_info(object):
    def setupUi(self, Frame_admini_info):
        Frame_admini_info.setObjectName("Frame_admini_info")
        Frame_admini_info.resize(513, 417)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame_admini_info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(Frame_admini_info)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Frame_admini_info)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(Frame_admini_info)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_aname = QtWidgets.QLineEdit(Frame_admini_info)
        self.lineEdit_aname.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_aname.setFont(font)
        self.lineEdit_aname.setObjectName("lineEdit_aname")
        self.verticalLayout.addWidget(self.lineEdit_aname)
        self.lineEdit_ano = QtWidgets.QLineEdit(Frame_admini_info)
        self.lineEdit_ano.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_ano.setFont(font)
        self.lineEdit_ano.setObjectName("lineEdit_ano")
        self.verticalLayout.addWidget(self.lineEdit_ano)
        self.lineEdit_asex = QtWidgets.QLineEdit(Frame_admini_info)
        self.lineEdit_asex.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_asex.setFont(font)
        self.lineEdit_asex.setObjectName("lineEdit_asex")
        self.verticalLayout.addWidget(self.lineEdit_asex)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.widget_password_change = QtWidgets.QWidget(Frame_admini_info)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.widget_password_change.setFont(font)
        self.widget_password_change.setObjectName("widget_password_change")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_password_change)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.widget_password_change)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_old = QtWidgets.QLineEdit(self.widget_password_change)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_old.setFont(font)
        self.lineEdit_old.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_old.setObjectName("lineEdit_old")
        self.gridLayout.addWidget(self.lineEdit_old, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_password_change)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_new1 = QtWidgets.QLineEdit(self.widget_password_change)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_new1.setFont(font)
        self.lineEdit_new1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new1.setObjectName("lineEdit_new1")
        self.gridLayout.addWidget(self.lineEdit_new1, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_password_change)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEdit_new2 = QtWidgets.QLineEdit(self.widget_password_change)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_new2.setFont(font)
        self.lineEdit_new2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new2.setObjectName("lineEdit_new2")
        self.gridLayout.addWidget(self.lineEdit_new2, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_password_change)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_change_password = QtWidgets.QPushButton(Frame_admini_info)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_change_password.setFont(font)
        self.pushButton_change_password.setObjectName("pushButton_change_password")
        self.horizontalLayout_2.addWidget(self.pushButton_change_password)
        self.pushButton_ensure = QtWidgets.QPushButton(Frame_admini_info)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_ensure.setFont(font)
        self.pushButton_ensure.setObjectName("pushButton_ensure")
        self.horizontalLayout_2.addWidget(self.pushButton_ensure)
        self.pushButton_cancel = QtWidgets.QPushButton(Frame_admini_info)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)

        self.retranslateUi(Frame_admini_info)
        QtCore.QMetaObject.connectSlotsByName(Frame_admini_info)

    def retranslateUi(self, Frame_admini_info):
        _translate = QtCore.QCoreApplication.translate
        Frame_admini_info.setWindowTitle(_translate("Frame_admini_info", "管理员信息"))
        self.label_5.setText(_translate("Frame_admini_info", "姓名"))
        self.label_6.setText(_translate("Frame_admini_info", "编号"))
        self.label_7.setText(_translate("Frame_admini_info", "性别"))
        self.label_8.setText(_translate("Frame_admini_info", "原密码"))
        self.label_9.setText(_translate("Frame_admini_info", "新密码"))
        self.label_10.setText(_translate("Frame_admini_info", "再次输入"))
        self.pushButton_change_password.setText(_translate("Frame_admini_info", "修改密码"))
        self.pushButton_ensure.setText(_translate("Frame_admini_info", "确认"))
        self.pushButton_cancel.setText(_translate("Frame_admini_info", "取消"))

