# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTuiFrame_login.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_login_1(object):
    def setupUi(self, Frame_login_1):
        Frame_login_1.setObjectName("Frame_login_1")
        Frame_login_1.resize(570, 479)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame_login_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_login = QtWidgets.QFrame(Frame_login_1)
        self.frame_login.setEnabled(True)
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_login)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.pushButton_hide = QtWidgets.QPushButton(self.frame_login)
        self.pushButton_hide.setEnabled(False)
        self.pushButton_hide.setText("")
        self.pushButton_hide.setAutoDefault(False)
        self.pushButton_hide.setDefault(True)
        self.pushButton_hide.setFlat(True)
        self.pushButton_hide.setObjectName("pushButton_hide")
        self.gridLayout_3.addWidget(self.pushButton_hide, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_login)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_login = QtWidgets.QPushButton(self.frame_login)
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout.addWidget(self.pushButton_login)
        self.pushButton_custer = QtWidgets.QPushButton(self.frame_login)
        self.pushButton_custer.setObjectName("pushButton_custer")
        self.verticalLayout.addWidget(self.pushButton_custer)
        self.pushButton_quit = QtWidgets.QPushButton(self.frame_login)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.verticalLayout.addWidget(self.pushButton_quit)
        self.gridLayout_4.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_Admini = QtWidgets.QRadioButton(self.frame_login)
        self.radioButton_Admini.setChecked(True)
        self.radioButton_Admini.setObjectName("radioButton_Admini")
        self.horizontalLayout.addWidget(self.radioButton_Admini)
        self.radioButton_cust = QtWidgets.QRadioButton(self.frame_login)
        self.radioButton_cust.setObjectName("radioButton_cust")
        self.horizontalLayout.addWidget(self.radioButton_cust)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.password = QtWidgets.QLineEdit(self.frame_login)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.label_username = QtWidgets.QLabel(self.frame_login)
        self.label_username.setObjectName("label_username")
        self.gridLayout.addWidget(self.label_username, 0, 0, 1, 1)
        self.username = QtWidgets.QLineEdit(self.frame_login)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 1, 1, 1)
        self.label_password = QtWidgets.QLabel(self.frame_login)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_warning = QtWidgets.QLabel(self.frame_login)
        self.label_warning.setEnabled(True)
        self.label_warning.setText("")
        self.label_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.label_warning.setObjectName("label_warning")
        self.gridLayout_4.addWidget(self.label_warning, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_login, 0, 0, 1, 1)

        self.retranslateUi(Frame_login_1)
        QtCore.QMetaObject.connectSlotsByName(Frame_login_1)
        Frame_login_1.setTabOrder(self.username, self.password)
        Frame_login_1.setTabOrder(self.password, self.radioButton_Admini)
        Frame_login_1.setTabOrder(self.radioButton_Admini, self.radioButton_cust)
        Frame_login_1.setTabOrder(self.radioButton_cust, self.pushButton_login)
        Frame_login_1.setTabOrder(self.pushButton_login, self.pushButton_custer)

    def retranslateUi(self, Frame_login_1):
        _translate = QtCore.QCoreApplication.translate
        Frame_login_1.setWindowTitle(_translate("Frame_login_1", "登录窗"))
        self.label_3.setText(_translate("Frame_login_1", "书店销售管理系统"))
        self.pushButton_login.setText(_translate("Frame_login_1", "登录"))
        self.pushButton_custer.setText(_translate("Frame_login_1", "游客进入"))
        self.pushButton_quit.setText(_translate("Frame_login_1", "退出"))
        self.radioButton_Admini.setText(_translate("Frame_login_1", "管理员"))
        self.radioButton_cust.setText(_translate("Frame_login_1", "售货员"))
        self.label_username.setText(_translate("Frame_login_1", "用户名"))
        self.label_password.setText(_translate("Frame_login_1", "密码"))

