# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTuiFrame_salesman_manage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_salesman_manage(object):
    def setupUi(self, Frame_salesman_manage):
        Frame_salesman_manage.setObjectName("Frame_salesman_manage")
        Frame_salesman_manage.resize(561, 419)
        self.gridLayout_5 = QtWidgets.QGridLayout(Frame_salesman_manage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label_SMno = QtWidgets.QLabel(Frame_salesman_manage)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_SMno.setFont(font)
        self.label_SMno.setObjectName("label_SMno")
        self.gridLayout.addWidget(self.label_SMno, 0, 1, 1, 1)
        self.lineEdit_SMno_choose = QtWidgets.QLineEdit(Frame_salesman_manage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_SMno_choose.setFont(font)
        self.lineEdit_SMno_choose.setObjectName("lineEdit_SMno_choose")
        self.gridLayout.addWidget(self.lineEdit_SMno_choose, 0, 2, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(Frame_salesman_manage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 0, 3, 1, 1)
        self.pushButton_choose = QtWidgets.QPushButton(Frame_salesman_manage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_choose.setFont(font)
        self.pushButton_choose.setObjectName("pushButton_choose")
        self.gridLayout.addWidget(self.pushButton_choose, 0, 4, 1, 1)
        self.pushButton_change = QtWidgets.QPushButton(Frame_salesman_manage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_change.setFont(font)
        self.pushButton_change.setObjectName("pushButton_change")
        self.gridLayout.addWidget(self.pushButton_change, 0, 5, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(Frame_salesman_manage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setObjectName("pushButton_del")
        self.gridLayout.addWidget(self.pushButton_del, 0, 6, 1, 1)
        self.pushButton_back = QtWidgets.QPushButton(Frame_salesman_manage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 0, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 8, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 44, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(Frame_salesman_manage)
        self.widget_3.setEnabled(True)
        self.widget_3.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_table2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_table2.setObjectName("verticalLayout_table2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_table_3_name = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_table_3_name.setFont(font)
        self.label_table_3_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_3_name.setObjectName("label_table_3_name")
        self.verticalLayout_7.addWidget(self.label_table_3_name)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_SMno_3 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_SMno_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_SMno_3.setFont(font)
        self.lineEdit_SMno_3.setText("")
        self.lineEdit_SMno_3.setObjectName("lineEdit_SMno_3")
        self.verticalLayout_9.addWidget(self.lineEdit_SMno_3)
        self.lineEdit_SMpassword_3 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_SMpassword_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_SMpassword_3.setFont(font)
        self.lineEdit_SMpassword_3.setObjectName("lineEdit_SMpassword_3")
        self.verticalLayout_9.addWidget(self.lineEdit_SMpassword_3)
        self.lineEdit_SMname_3 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_SMname_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_SMname_3.setFont(font)
        self.lineEdit_SMname_3.setObjectName("lineEdit_SMname_3")
        self.verticalLayout_9.addWidget(self.lineEdit_SMname_3)
        self.comboBox_SMsex_3 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_SMsex_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_SMsex_3.setFont(font)
        self.comboBox_SMsex_3.setObjectName("comboBox_SMsex_3")
        self.comboBox_SMsex_3.addItem("")
        self.comboBox_SMsex_3.addItem("")
        self.comboBox_SMsex_3.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_SMsex_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_table2.addLayout(self.verticalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_table2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Frame_salesman_manage)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_tabel1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_tabel1.setObjectName("verticalLayout_tabel1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_table_name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_table_name.setFont(font)
        self.label_table_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table_name.setObjectName("label_table_name")
        self.verticalLayout_3.addWidget(self.label_table_name)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_SMno = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_SMno.setFont(font)
        self.lineEdit_SMno.setObjectName("lineEdit_SMno")
        self.verticalLayout.addWidget(self.lineEdit_SMno)
        self.lineEdit_SMpassword = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_SMpassword.setFont(font)
        self.lineEdit_SMpassword.setObjectName("lineEdit_SMpassword")
        self.verticalLayout.addWidget(self.lineEdit_SMpassword)
        self.lineEdit_SMname = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_SMname.setFont(font)
        self.lineEdit_SMname.setObjectName("lineEdit_SMname")
        self.verticalLayout.addWidget(self.lineEdit_SMname)
        self.comboBox_SMsex = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_SMsex.setFont(font)
        self.comboBox_SMsex.setObjectName("comboBox_SMsex")
        self.comboBox_SMsex.addItem("")
        self.comboBox_SMsex.addItem("")
        self.verticalLayout.addWidget(self.comboBox_SMsex)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_tabel1.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout_tabel1, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Frame_salesman_manage)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem5 = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(Frame_salesman_manage)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButton_pre_view = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_pre_view.setFont(font)
        self.pushButton_pre_view.setObjectName("pushButton_pre_view")
        self.horizontalLayout_3.addWidget(self.pushButton_pre_view)
        self.pushButton_pre_view_cancel = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_pre_view_cancel.setFont(font)
        self.pushButton_pre_view_cancel.setObjectName("pushButton_pre_view_cancel")
        self.horizontalLayout_3.addWidget(self.pushButton_pre_view_cancel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.gridLayout_2.addWidget(self.widget_4, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 1, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 3, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 125, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 4, 1, 1, 1)

        self.retranslateUi(Frame_salesman_manage)
        QtCore.QMetaObject.connectSlotsByName(Frame_salesman_manage)

    def retranslateUi(self, Frame_salesman_manage):
        _translate = QtCore.QCoreApplication.translate
        Frame_salesman_manage.setWindowTitle(_translate("Frame_salesman_manage", "销售人员管理"))
        self.label_SMno.setText(_translate("Frame_salesman_manage", "登录名"))
        self.pushButton_add.setText(_translate("Frame_salesman_manage", "添加"))
        self.pushButton_choose.setText(_translate("Frame_salesman_manage", "选定"))
        self.pushButton_change.setText(_translate("Frame_salesman_manage", "修改"))
        self.pushButton_del.setText(_translate("Frame_salesman_manage", "删除"))
        self.pushButton_back.setText(_translate("Frame_salesman_manage", "返回"))
        self.label_table_3_name.setText(_translate("Frame_salesman_manage", "销售人员信息"))
        self.label_19.setText(_translate("Frame_salesman_manage", "登录名"))
        self.label_20.setText(_translate("Frame_salesman_manage", "密码"))
        self.label_21.setText(_translate("Frame_salesman_manage", "用户名"))
        self.label_22.setText(_translate("Frame_salesman_manage", "性别"))
        self.comboBox_SMsex_3.setCurrentText(_translate("Frame_salesman_manage", "无"))
        self.comboBox_SMsex_3.setItemText(0, _translate("Frame_salesman_manage", "无"))
        self.comboBox_SMsex_3.setItemText(1, _translate("Frame_salesman_manage", "女"))
        self.comboBox_SMsex_3.setItemText(2, _translate("Frame_salesman_manage", "男"))
        self.label_table_name.setText(_translate("Frame_salesman_manage", "销售人员信息"))
        self.label_2.setText(_translate("Frame_salesman_manage", "登录名"))
        self.label_3.setText(_translate("Frame_salesman_manage", "密码"))
        self.label_4.setText(_translate("Frame_salesman_manage", "用户名"))
        self.label_5.setText(_translate("Frame_salesman_manage", "性别"))
        self.comboBox_SMsex.setItemText(0, _translate("Frame_salesman_manage", "女"))
        self.comboBox_SMsex.setItemText(1, _translate("Frame_salesman_manage", "男"))
        self.pushButton_cancel.setText(_translate("Frame_salesman_manage", "取消"))
        self.pushButton_pre_view.setText(_translate("Frame_salesman_manage", "预览"))
        self.pushButton_pre_view_cancel.setText(_translate("Frame_salesman_manage", "取消"))

