# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTuiFrame_see_member_info.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_see_member_info(object):
    def setupUi(self, Frame_see_member_info):
        Frame_see_member_info.setObjectName("Frame_see_member_info")
        Frame_see_member_info.resize(563, 434)
        font = QtGui.QFont()
        font.setPointSize(14)
        Frame_see_member_info.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Frame_see_member_info)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_mno = QtWidgets.QRadioButton(Frame_see_member_info)
        self.radioButton_mno.setObjectName("radioButton_mno")
        self.horizontalLayout_2.addWidget(self.radioButton_mno)
        self.radioButton_mname = QtWidgets.QRadioButton(Frame_see_member_info)
        self.radioButton_mname.setObjectName("radioButton_mname")
        self.horizontalLayout_2.addWidget(self.radioButton_mname)
        self.radioButton_mtel = QtWidgets.QRadioButton(Frame_see_member_info)
        self.radioButton_mtel.setChecked(True)
        self.radioButton_mtel.setObjectName("radioButton_mtel")
        self.horizontalLayout_2.addWidget(self.radioButton_mtel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_seach_text = QtWidgets.QLineEdit(Frame_see_member_info)
        self.lineEdit_seach_text.setObjectName("lineEdit_seach_text")
        self.horizontalLayout_3.addWidget(self.lineEdit_seach_text)
        self.pushButton_see = QtWidgets.QPushButton(Frame_see_member_info)
        self.pushButton_see.setObjectName("pushButton_see")
        self.horizontalLayout_3.addWidget(self.pushButton_see)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_hint = QtWidgets.QLabel(Frame_see_member_info)
        self.label_hint.setText("")
        self.label_hint.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hint.setObjectName("label_hint")
        self.verticalLayout_3.addWidget(self.label_hint)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Frame_see_member_info)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Frame_see_member_info)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Frame_see_member_info)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Frame_see_member_info)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Frame_see_member_info)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Frame_see_member_info)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.widget = QtWidgets.QWidget(Frame_see_member_info)
        self.widget.setEnabled(True)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_mno = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_mno.setEnabled(False)
        self.lineEdit_mno.setObjectName("lineEdit_mno")
        self.verticalLayout_2.addWidget(self.lineEdit_mno)
        self.lineEdit_manme = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_manme.setEnabled(False)
        self.lineEdit_manme.setObjectName("lineEdit_manme")
        self.verticalLayout_2.addWidget(self.lineEdit_manme)
        self.lineEdit_msex = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_msex.setEnabled(False)
        self.lineEdit_msex.setObjectName("lineEdit_msex")
        self.verticalLayout_2.addWidget(self.lineEdit_msex)
        self.lineEdit_mtel = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_mtel.setEnabled(False)
        self.lineEdit_mtel.setObjectName("lineEdit_mtel")
        self.verticalLayout_2.addWidget(self.lineEdit_mtel)
        self.lineEdit_mbirth = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_mbirth.setEnabled(False)
        self.lineEdit_mbirth.setObjectName("lineEdit_mbirth")
        self.verticalLayout_2.addWidget(self.lineEdit_mbirth)
        self.lineEdit_minte = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_minte.setEnabled(False)
        self.lineEdit_minte.setObjectName("lineEdit_minte")
        self.verticalLayout_2.addWidget(self.lineEdit_minte)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_change = QtWidgets.QPushButton(Frame_see_member_info)
        self.pushButton_change.setEnabled(False)
        self.pushButton_change.setObjectName("pushButton_change")
        self.horizontalLayout_4.addWidget(self.pushButton_change)
        self.pushButton_ensure = QtWidgets.QPushButton(Frame_see_member_info)
        self.pushButton_ensure.setEnabled(False)
        self.pushButton_ensure.setObjectName("pushButton_ensure")
        self.horizontalLayout_4.addWidget(self.pushButton_ensure)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.pushButton_back = QtWidgets.QPushButton(Frame_see_member_info)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 0, 2, 1, 1)

        self.retranslateUi(Frame_see_member_info)
        QtCore.QMetaObject.connectSlotsByName(Frame_see_member_info)

    def retranslateUi(self, Frame_see_member_info):
        _translate = QtCore.QCoreApplication.translate
        Frame_see_member_info.setWindowTitle(_translate("Frame_see_member_info", "查看会员信息"))
        self.radioButton_mno.setText(_translate("Frame_see_member_info", "会员号"))
        self.radioButton_mname.setText(_translate("Frame_see_member_info", "会员名"))
        self.radioButton_mtel.setText(_translate("Frame_see_member_info", "电话号码"))
        self.pushButton_see.setText(_translate("Frame_see_member_info", "搜索"))
        self.label.setText(_translate("Frame_see_member_info", "会员号"))
        self.label_2.setText(_translate("Frame_see_member_info", "会员名"))
        self.label_3.setText(_translate("Frame_see_member_info", "性别"))
        self.label_4.setText(_translate("Frame_see_member_info", "电话号码 "))
        self.label_5.setText(_translate("Frame_see_member_info", "生日"))
        self.label_6.setText(_translate("Frame_see_member_info", "积分"))
        self.pushButton_change.setText(_translate("Frame_see_member_info", "修改"))
        self.pushButton_ensure.setText(_translate("Frame_see_member_info", "确认"))
        self.pushButton_back.setText(_translate("Frame_see_member_info", "返回"))

