# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTuiFrame_sales_man.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_sales_man(object):
    def setupUi(self, Frame_sales_man):
        Frame_sales_man.setObjectName("Frame_sales_man")
        Frame_sales_man.resize(810, 516)
        font = QtGui.QFont()
        font.setPointSize(14)
        Frame_sales_man.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Frame_sales_man)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_sm_menu = QtWidgets.QWidget(Frame_sales_man)
        self.widget_sm_menu.setObjectName("widget_sm_menu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_sm_menu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_menu_search = QtWidgets.QPushButton(self.widget_sm_menu)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_menu_search.setFont(font)
        self.pushButton_menu_search.setObjectName("pushButton_menu_search")
        self.horizontalLayout.addWidget(self.pushButton_menu_search)
        self.pushButton_menu_book_back = QtWidgets.QPushButton(self.widget_sm_menu)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_menu_book_back.setFont(font)
        self.pushButton_menu_book_back.setObjectName("pushButton_menu_book_back")
        self.horizontalLayout.addWidget(self.pushButton_menu_book_back)
        self.pushButton_menu_buy = QtWidgets.QPushButton(self.widget_sm_menu)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_menu_buy.setFont(font)
        self.pushButton_menu_buy.setObjectName("pushButton_menu_buy")
        self.horizontalLayout.addWidget(self.pushButton_menu_buy)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_menu_see_member = QtWidgets.QPushButton(self.widget_sm_menu)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_menu_see_member.setFont(font)
        self.pushButton_menu_see_member.setObjectName("pushButton_menu_see_member")
        self.horizontalLayout_2.addWidget(self.pushButton_menu_see_member)
        self.pushButton_menu_become_member = QtWidgets.QPushButton(self.widget_sm_menu)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_menu_become_member.setFont(font)
        self.pushButton_menu_become_member.setObjectName("pushButton_menu_become_member")
        self.horizontalLayout_2.addWidget(self.pushButton_menu_become_member)
        self.pushButton_menu_sm_info = QtWidgets.QPushButton(self.widget_sm_menu)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_menu_sm_info.setFont(font)
        self.pushButton_menu_sm_info.setObjectName("pushButton_menu_sm_info")
        self.horizontalLayout_2.addWidget(self.pushButton_menu_sm_info)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.pushButton_back = QtWidgets.QPushButton(self.widget_sm_menu)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_3.addWidget(self.pushButton_back)
        self.pushButton_quit = QtWidgets.QPushButton(self.widget_sm_menu)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout_3.addWidget(self.pushButton_quit)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_sm_menu, 0, 0, 1, 1)

        self.retranslateUi(Frame_sales_man)
        QtCore.QMetaObject.connectSlotsByName(Frame_sales_man)
        Frame_sales_man.setTabOrder(self.pushButton_menu_search, self.pushButton_menu_book_back)
        Frame_sales_man.setTabOrder(self.pushButton_menu_book_back, self.pushButton_menu_buy)
        Frame_sales_man.setTabOrder(self.pushButton_menu_buy, self.pushButton_menu_see_member)
        Frame_sales_man.setTabOrder(self.pushButton_menu_see_member, self.pushButton_menu_become_member)

    def retranslateUi(self, Frame_sales_man):
        _translate = QtCore.QCoreApplication.translate
        Frame_sales_man.setWindowTitle(_translate("Frame_sales_man", "销售人员"))
        self.pushButton_menu_search.setText(_translate("Frame_sales_man", "图书搜索"))
        self.pushButton_menu_book_back.setText(_translate("Frame_sales_man", "退货"))
        self.pushButton_menu_buy.setText(_translate("Frame_sales_man", "购买"))
        self.pushButton_menu_see_member.setText(_translate("Frame_sales_man", "会员信息查看/修改"))
        self.pushButton_menu_become_member.setText(_translate("Frame_sales_man", "成为会员"))
        self.pushButton_menu_sm_info.setText(_translate("Frame_sales_man", "个人信息管理"))
        self.pushButton_back.setText(_translate("Frame_sales_man", "返回"))
        self.pushButton_quit.setText(_translate("Frame_sales_man", "退出"))

