# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTuiFrame_sm_info.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame_sm_info(object):
    def setupUi(self, Frame_sm_info):
        Frame_sm_info.setObjectName("Frame_sm_info")
        Frame_sm_info.resize(450, 364)
        font = QtGui.QFont()
        font.setPointSize(14)
        Frame_sm_info.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Frame_sm_info)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_back = QtWidgets.QPushButton(Frame_sm_info)
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Frame_sm_info)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Frame_sm_info)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Frame_sm_info)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_smname = QtWidgets.QLineEdit(Frame_sm_info)
        self.lineEdit_smname.setEnabled(False)
        self.lineEdit_smname.setObjectName("lineEdit_smname")
        self.verticalLayout_2.addWidget(self.lineEdit_smname)
        self.lineEdit_smno = QtWidgets.QLineEdit(Frame_sm_info)
        self.lineEdit_smno.setEnabled(False)
        self.lineEdit_smno.setObjectName("lineEdit_smno")
        self.verticalLayout_2.addWidget(self.lineEdit_smno)
        self.lineEdit_smsex = QtWidgets.QLineEdit(Frame_sm_info)
        self.lineEdit_smsex.setEnabled(False)
        self.lineEdit_smsex.setObjectName("lineEdit_smsex")
        self.verticalLayout_2.addWidget(self.lineEdit_smsex)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.widget_password_change = QtWidgets.QWidget(Frame_sm_info)
        self.widget_password_change.setObjectName("widget_password_change")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_password_change)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_password_change)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget_password_change)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget_password_change)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_old = QtWidgets.QLineEdit(self.widget_password_change)
        self.lineEdit_old.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_old.setObjectName("lineEdit_old")
        self.verticalLayout_4.addWidget(self.lineEdit_old)
        self.lineEdit_new1 = QtWidgets.QLineEdit(self.widget_password_change)
        self.lineEdit_new1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new1.setObjectName("lineEdit_new1")
        self.verticalLayout_4.addWidget(self.lineEdit_new1)
        self.lineEdit_new2 = QtWidgets.QLineEdit(self.widget_password_change)
        self.lineEdit_new2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new2.setObjectName("lineEdit_new2")
        self.verticalLayout_4.addWidget(self.lineEdit_new2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.widget_password_change)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_change_password = QtWidgets.QPushButton(Frame_sm_info)
        self.pushButton_change_password.setObjectName("pushButton_change_password")
        self.horizontalLayout_3.addWidget(self.pushButton_change_password)
        self.pushButton_ensure = QtWidgets.QPushButton(Frame_sm_info)
        self.pushButton_ensure.setObjectName("pushButton_ensure")
        self.horizontalLayout_3.addWidget(self.pushButton_ensure)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)

        self.retranslateUi(Frame_sm_info)
        QtCore.QMetaObject.connectSlotsByName(Frame_sm_info)

    def retranslateUi(self, Frame_sm_info):
        _translate = QtCore.QCoreApplication.translate
        Frame_sm_info.setWindowTitle(_translate("Frame_sm_info", "销售人员信息"))
        self.pushButton_back.setText(_translate("Frame_sm_info", "返回"))
        self.label.setText(_translate("Frame_sm_info", "姓名"))
        self.label_2.setText(_translate("Frame_sm_info", "编号"))
        self.label_3.setText(_translate("Frame_sm_info", "性别"))
        self.label_4.setText(_translate("Frame_sm_info", "原密码"))
        self.label_5.setText(_translate("Frame_sm_info", "新密码"))
        self.label_6.setText(_translate("Frame_sm_info", "再次输入"))
        self.pushButton_change_password.setText(_translate("Frame_sm_info", "修改密码"))
        self.pushButton_ensure.setText(_translate("Frame_sm_info", "确认"))

